# tag::hostname[]
mongo.hostname=mongodb
# end::hostname[]
# tag::port[]
mongo.port=27017
# end::port[]
# tag::dbname[]
mongo.dbname=admin
# end::dbname[]
# tag::mongoUser[]
mongo.user=admin
# end::mongoUser[]
# tag::passEncoded[]
mongo.pass.encoded=secret
# tag::passEncoded[]