mongo.host=localhost
mongo.port=27017
mongo.database=appdb
mongo.username=admin
mongo.password=appdb

mp.jwt.verify.issuer=LakerTracks
mp.jwt.verify.publickey.location=${server.config.dir}/resources/security/publickey.pem
mp.jwt.verify.publickey.algorithm=RS256
mp.jwt.verify.audiences=worklog